import re

kotlin_code = """
ImmutableMap.builder().put(
            "notification" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                IHCHHORIOCCIROCRHCOHHIROICCIRO::class.java,
                { string -> IHCHHORIOCCIROCRHCOHHIROICCIRO() }) as Any?
        ).put(
            "language" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                CIRCIRHCCIOIIRORRORHIHICOIORCI::class.java,
                { string -> CIRCIRHCCIOIIRORRORHIHICOIORCI() }) as Any?
        ).put(
            "metadata" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HOOICOHRHRIHORCOIICCRRIHHOIRIC::class.java,
                { string -> HOOICOHRHRIHORCOIICCRRIHHOIRIC() }) as Any?
        ).put(
            "accounts" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.IOHCRIOROICRICIICHRHCCORHROOCO.IOHCRIOROICRICIICHRHCCORHROOCO::class.java,
                { string -> IOHCRIOROICRICIICHRHCCORHROOCO() }) as Any?
        ).put(
            "alerts" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.IOHCRIOROICRICIICHRHCCORHROOCO.HIRCORCRRIIHCRHRIRCHCIHOCHIRIR::class.java,
                { string -> HIRCORCRRIIHCRHRIRCHCIHOCHIRIR() }) as Any?
        ).put(
            "blogPosts" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.IOHCRIOROICRICIICHRHCCORHROOCO.HCCICHOOHHOIHRRCROCROHRIIOHOCC::class.java,
                { string -> HCCICHOOHHOIHRRCROCROHRIIOHOCC() }) as Any?
        ).put(
            "homeButtons" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.IOHCRIOROICRICIICHRHCCORHROOCO.IIRHRHIOCCRICHIIROHHCHOHROIHHH::class.java,
                { string -> IIRHRHIOCCRICHIIROHHCHOHROIHHH() }) as Any?
        ).put(
            "homeNavigation" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.IOHCRIOROICRICIICHRHCCORHROOCO.CIRCIRHCCIOIIRORRORHIHICOIORCI::class.java,
                { string -> CIRCIRHCCIOIIRORRORHIHICOIORCI() }) as Any?
        ).put(
            "savedSkins" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                RRHIIIRIHOHOHRCHHRRHOCIOICCRCC::class.java,
                { string -> RRHIIIRIHOHOHRCHHRRHOCIOICCRCC() }) as Any?
        ).put(
            "socialMedia" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.IOHCRIOROICRICIICHRHCCORHROOCO.HOOICOHRHRIHORCOIICCRRIHHOIRIC::class.java,
                { string -> HOOICOHRHRIHORCOIICCRRIHHOIRIC() }) as Any?
        ).put(
            "homeTheme" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.IOHCRIOROICRICIICHRHCCORHROOCO.HOCCRHIRRRCCCCCOCICCHOHIHCIRIH::class.java,
                { string -> HOCCRHIRRRCCCCCOCICCHOHIHCIRIH() }) as Any?
        ).put(
            "homeRadio" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.IOHCRIOROICRICIICHRHCCORHROOCO.HRRIHRRICRORHHRIIOIOHOOHIHIRIC::class.java,
                { string -> HRRIHRRICRORHHRIIOIOHOOHIHIRIC() }) as Any?
        ).put(
            "profiles" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                IOHOCCRICRHHHRICIIHCIOIRCRHCRI::class.java,
                { string -> IOHOCCRICRHHHRICIIHCIOIRCRHCRI() }) as Any?
        ).put(
            "settings" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                CCRCCHOOHCHHCIORHHCHIIICCRHRIO::class.java,
                { string -> CCRCCHOOHCHHCIORHHCHIIICCRHRIO() }) as Any?
        ).put(
            "waypoints" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                HCIHCCHOOHRHHICCOCCCRIRHOHHRHC::class.java,
                { string -> HCIHCCHOOHRHHICCOCCCRIRHOHHRHC() }) as Any?
        ).put(
            "cosmetics" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HIRCORCRRIIHCRHRIRCHCIHOCHIRIR::class.java,
                { string -> HIRCORCRRIIHCRHRIRCHCIHOCHIRIR() }) as Any?
        ).put(
            "lunarPlus" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                HOCCRHIRRRCCCCCOCICCHOHIHCIRIH::class.java,
                { string -> HOCCRHIRRRCCCCCOCICCHOHIHCIRIH() }) as Any?
        ).put(
            "emotes" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HCCICHOOHHOIHRRCROCROHRIIOHOCC::class.java,
                { string -> HCCICHOOHHOIHRRCROCROHRIIOHOCC() }) as Any?
        ).put(
            "lockerSettings" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HRRIHRRICRORHHRIIOIOHOOHIHIRIC::class.java,
                { string -> HRRIHRRICRORHHRIIOIOHOOHIHIRIC() }) as Any?
        ).put(
            "styngr" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                OHORCRCROIOHHROHHCICIHHCRRRRHI::class.java,
                { string -> OHORCRCROIOHHROHHCICIHHCRRRRHI() }) as Any?
        ).put(
            "mods" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HIRCORCRRIIHCRHRIRCHCIHOCHIRIR.IIRHRHIOCCRICHIIROHHCHOHROIHHH::class.java,
                { string -> IIRHRHIOCCRICHIIROHHCHOHROIHHH() }) as Any?
        ).put(
            "hudModProperty" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HIRCORCRRIIHCRHRIRCHCIHOCHIRIR.HCCICHOOHHOIHRRCROCROHRIIOHOCC::class.java,
                { com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HIRCORCRRIIHCRHRIRCHCIHOCHIRIR.HCCICHOOHHOIHRRCROCROHRIIOHOCC() }) as Any?
        ).put(
            "hudModMetadata" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HIRCORCRRIIHCRHRIRCHCIHOCHIRIR.HIRCORCRRIIHCRHRIRCHCIHOCHIRIR::class.java,
                { com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HIRCORCRRIIHCRHRIRCHCIHOCHIRIR.HIRCORCRRIIHCRHRIRCHCIHOCHIRIR() }) as Any?
        ).put(
            "assetsClient" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HCCICHOOHHOIHRRCROCROHRIIOHOCC.IOHCRIOROICRICIICHRHCCORHROOCO::class.java,
                { string -> IOHCRIOROICRICIICHRHCCORHROOCO() }) as Any?
        ).put(
            "friends" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                HCCICHOOHHOIHRRCROCROHRIIOHOCC::class.java,
                { string -> HCCICHOOHHOIHRRCROCROHRIIOHOCC() }) as Any?
        ).put(
            "friendsChat" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HIRCORCRRIIHCRHRIRCHCIHOCHIRIR::class.java,
                { string -> HIRCORCRRIIHCRHRIRCHCIHOCHIRIR() }) as Any?
        ).put(
            "hostedWorlds" as Any,
            com.moonsworth.lunar.IHCHHORIOCCIROCRHCOHHIROICCIRO.CIRCIRHCCIOIIRORRORHIHICOIORCI.IIRHRHIOCCRICHIIROHHCHOHROIHHH.OOCHIHCOOCIROHORRIOHIRCIOCIHOC(
                com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.IIRHRHIOCCRICHIIROHHCHOHROIHHH::class.java,
                { string -> IIRHRHIOCCRICHIIROHHCHOHROIHHH() }) as Any?
        ).build()
"""

imports_code = """
import com.moonsworth.lunar.IOHCRIOROICRICIICHRHCCORHROOCO.CIRCIRHCCIOIIRORRORHIHICOIORCI.HIRCORCRRIIHCRHRIRCHCIHOCHIRIR.RHOHOHRIHROHOIRROCROOIHCICCRHI;
import com.moonsworth.lunar.IOHCRIOROICRICIICHRHCCORHROOCO.CIRCIRHCCIOIIRORRORHIHICOIORCI.HIRCORCRRIIHCRHRIRCHCIHOCHIRIR.RRHRIRCCRHIOOOIOORHICHHHRICRIO;
import com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HIRCORCRRIIHCRHRIRCHCIHOCHIRIR;
import com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.CCRCCHOOHCHHCIORHHCHIIICCRHRIO;
import com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.CIRCIRHCCIOIIRORRORHIHICOIORCI;
import com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HCCICHOOHHOIHRRCROCROHRIIOHOCC;
import com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HCIHCCHOOHRHHICCOCCCRIRHOHHRHC;
import com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HOCCRHIRRRCCCCCOCICCHOHIHCIRIH;
import com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.IHCHHORIOCCIROCRHCOHHIROICCIRO;
import com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.IOHOCCRICRHHHRICIIHCIOIRCRHCRI;
import com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.OHORCRCROIOHHROHHCICIHHCRRRRHI;
import com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.RRHIIIRIHOHOHRCHHRRHOCIOICCRCC;
import com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.IOHCRIOROICRICIICHRHCCORHROOCO;
import com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.IOHCRIOROICRICIICHRHCCORHROOCO.HOOICOHRHRIHORCOIICCRRIHHOIRIC;
import com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.IOHCRIOROICRICIICHRHCCORHROOCO.HRRIHRRICRORHHRIIOIOHOOHIHIRIC;
import com.moonsworth.lunar.client.OHHRIOHICHOCCIHOCRIIRCIHRHHOCC.ICCIICHOOHRRHRCCICCOIRHRRHIROH;
"""

pattern = re.compile(
    r'\.put\(\s*"([^"]+)"\s+as Any,\s+.*?\(\s*([\w\.]+)::class\.java', re.DOTALL
)

matches = pattern.findall(kotlin_code)

pattern = re.compile(r'import\s+([\w\.]+);')
import_matches = pattern.findall(imports_code)
imports = {}
for full_path in import_matches:
    class_name = full_path.split(".")[-1]
    imports[class_name] = full_path

print("mapOf(")
for key, class_name in matches:
    if "." not in class_name:
        class_name = imports[class_name]
    print(f"    \"{class_name}\" to \"{key}\",")
print(")")
