package org.cubewhy.reverse.codegen

object NamespaceMapper {
    // Generated via scripts/extract_namespace.py
    private val namespaceMap = mapOf(
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.IHCHHORIOCCIROCRHCOHHIROICCIRO" to "notification",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.CIRCIRHCCIOIIRORRORHIHICOIORCI" to "language",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HOOICOHRHRIHORCOIICCRRIHHOIRIC" to "metadata",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.IOHCRIOROICRICIICHRHCCORHROOCO.IOHCRIOROICRICIICHRHCCORHROOCO" to "accounts",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.IOHCRIOROICRICIICHRHCCORHROOCO.HIRCORCRRIIHCRHRIRCHCIHOCHIRIR" to "alerts",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.IOHCRIOROICRICIICHRHCCORHROOCO.HCCICHOOHHOIHRRCROCROHRIIOHOCC" to "blogPosts",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.IOHCRIOROICRICIICHRHCCORHROOCO.IIRHRHIOCCRICHIIROHHCHOHROIHHH" to "homeButtons",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.IOHCRIOROICRICIICHRHCCORHROOCO.CIRCIRHCCIOIIRORRORHIHICOIORCI" to "homeNavigation",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.RRHIIIRIHOHOHRCHHRRHOCIOICCRCC" to "savedSkins",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.IOHCRIOROICRICIICHRHCCORHROOCO.HOOICOHRHRIHORCOIICCRRIHHOIRIC" to "socialMedia",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.IOHCRIOROICRICIICHRHCCORHROOCO.HOCCRHIRRRCCCCCOCICCHOHIHCIRIH" to "homeTheme",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.IOHCRIOROICRICIICHRHCCORHROOCO.HRRIHRRICRORHHRIIOIOHOOHIHIRIC" to "homeRadio",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.IOHOCCRICRHHHRICIIHCIOIRCRHCRI" to "profiles",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.CCRCCHOOHCHHCIORHHCHIIICCRHRIO" to "settings",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HCIHCCHOOHRHHICCOCCCRIRHOHHRHC" to "waypoints",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HIRCORCRRIIHCRHRIRCHCIHOCHIRIR" to "cosmetics",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HOCCRHIRRRCCCCCOCICCHOHIHCIRIH" to "lunarPlus",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HCCICHOOHHOIHRRCROCROHRIIOHOCC" to "emotes",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HRRIHRRICRORHHRIIOIOHOOHIHIRIC" to "lockerSettings",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.OHORCRCROIOHHROHHCICIHHCRRRRHI" to "styngr",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HIRCORCRRIIHCRHRIRCHCIHOCHIRIR.IIRHRHIOCCRICHIIROHHCHOHROIHHH" to "mods",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HIRCORCRRIIHCRHRIRCHCIHOCHIRIR.HCCICHOOHHOIHRRCROCROHRIIOHOCC" to "hudModProperty",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HIRCORCRRIIHCRHRIRCHCIHOCHIRIR.HIRCORCRRIIHCRHRIRCHCIHOCHIRIR" to "hudModMetadata",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HCCICHOOHHOIHRRCROCROHRIIOHOCC.IOHCRIOROICRICIICHRHCCORHROOCO" to "assetsClient",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HCCICHOOHHOIHRRCROCROHRIIOHOCC" to "friends",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HIRCORCRRIIHCRHRIRCHCIHOCHIRIR" to "friendsChat",
        "com.moonsworth.lunar.client.HOHCOOCHHICCOOHCIRHRCOICORRRRI.HCCICHOOHHOIHRRCROCROHRIIOHOCC.HRRIHRRICRORHHRIIOIOHOOHIHIRIC.IOHCRIOROICRICIICHRHCCORHROOCO.IIRHRHIOCCRICHIIROHHCHOHROIHHH" to "hostedWorlds",
    )

    /**
     * Map classname to namespace
     *
     * @return the namespace. Default to the root namespace
     * */
    fun mapNamespace(className: String): String? {
        return namespaceMap[className.replace("/", ".")]
    }
}
